Site\CoreBundle\Entity\News:
    type: entity
    repositoryClass: Site\CoreBundle\Entity\Repository\NewsRepository
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: text
        date:
            type: string
            length: 255
        article:
            type: text
    manyToMany:
        tagInf:
            targetEntity: Tags
            inversedBy: newsInf
            joinTable:
                name: NewsTagsConn
                joinColumns:
                    news_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
